# Uncomment this line to define a global platform for your project
 platform :ios, ‘8.0’

target 'swiftGuDong' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'AMap3DMap', '~> 4.1.0'  #3D地图SDK
  pod 'AMapSearch' #搜索服务SDK
end
